name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dockerfile: [
          "fuzzy",
          "fuzzy-numpy",
          "fuzzy-numpy-scipy",
          "fuzzy-numpy-scipy-sklearn"
        ]
    steps:
    - name: Build the Docker image
      run: |
        docker build . --file ../Dockerfile.${{ matrix.dockerfile }} --tag ${{ matrix.dockerfile }}:$(date +%s)